# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\KnowledgeMap\PDF_Process\GUI\Process_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.SourceButton.setGeometry(QtCore.QRect(200, 100, 120, 30))
        self.SourceButton.setObjectName("SourceButton")
        self.TargetButton = QtWidgets.QPushButton(self.centralwidget)
        self.TargetButton.setGeometry(QtCore.QRect(200, 200, 120, 30))
        self.TargetButton.setObjectName("TargetButton")
        self.Process = QtWidgets.QPushButton(self.centralwidget)
        self.Process.setGeometry(QtCore.QRect(600, 360, 93, 28))
        self.Process.setObjectName("Process")
        self.SourceFolder = QtWidgets.QTextBrowser(self.centralwidget)
        self.SourceFolder.setGeometry(QtCore.QRect(370, 100, 300, 30))
        self.SourceFolder.setObjectName("SourceFolder")
        self.TargetFolder = QtWidgets.QTextBrowser(self.centralwidget)
        self.TargetFolder.setGeometry(QtCore.QRect(370, 200, 300, 30))
        self.TargetFolder.setObjectName("TargetFolder")
        self.ProcessText = QtWidgets.QTextBrowser(self.centralwidget)
        self.ProcessText.setGeometry(QtCore.QRect(600, 410, 93, 28))
        self.ProcessText.setObjectName("ProcessText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SourceButton.setText(_translate("MainWindow", "选择源文件夹"))
        self.TargetButton.setText(_translate("MainWindow", "选择目标文件夹"))
        self.Process.setText(_translate("MainWindow", "运行"))
